#+TITLE: Resume
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[margin=0.9in]{geometry}
#+LATEX_HEADER: \usepackage{titling} \setlength{\droptitle}{-2.5cm}
#+OPTIONS: author:nil num:1 toc:nil date:nil

  #+BEGIN_CENTER
  Ahnaf Siddiqi | http://remmihsorp.github.io | ahnafsidd@gmail.com
  #+END_CENTER

  #+BEGIN_EXAMPLE
  This is a full resume with a focus on content. For a more abridged version for
  application purposes, please contact me.
  #+END_EXAMPLE

** Education

   (/Class of 2016/) > *Singapore University of Technology and Design*

   Bachelor of Engineering with major in Information Systems Technology and Design. \\
   Focus Tracks: Security and Communications, Artificial Intelligence.

   (/Class of 2011/) > *GCE Cambridge A-Levels*

** Experience

   (/November 2016 - Present/) > *Research Assistant @ Singapore University of Technology and Design*
   - Observed Ethernet/IP packets in wireshark to understand Common Industrial Protocol (CIP).
   - Reconstruced CIP packets for both TCP and UDP sections for respective layers.
   - Developed an abstracted simulation package for CIP utilizing TDD.
   - Used SOLI(D) principles to the best of my ability to create a reasonably good api.
   - Open sourced CIP libraries like /pycomm/ (client library) can succesfully interact with the simulated environment.
   - The implemented TCP section of the library was used as part of a challenge in an international inter-university CTF competition (Secure Cyber-Physical Systems at SUTD)
   - Developed a separate web challenge which included password cracking, very basic reconnaissance, and command injection. This was abstracted from real vulnerablities of a wireless moxa server.
   - Hosted the challenge in Amazon S3.
   - /Tech Knowledge/: Python3, Nose, Wireshark, Linux Containers, Flask, C, Busybox compilation.

   (/October 2016 - January 2017/) > *Web Developer @ Souschef*
   - Worked in a small team of 3 to develop a web application in nodejs.
   - Application was configuration panel which took updated database with user input and subsequently distributed them accross multiple remote machines (prototypes) at different outlets.
   - Remote machines were liquid dispenser prototypes which where automatically synchronized after a new update was dispersed.
   - Part time job to perform to improve on the fundamentals of js non-blocking environment.
   - Used TDD for the entire project.
   - /Tech Knowledge/: Express JS, Node, HTML5, CSS, vanilla Javascript, and other express packages.

   (/August - September 2016/) > *Teaching Assistant @ General Assembly*
   - Aided instructor in teaching basics of CLI, GIT, HTML, Javascript, and ExpressJS to students.
   - Managed several tasks for the course which included homework checking, programming test, and projects.

   (/May - August 2015/) > *Web Developer Intern @ Tinkerbox Studios*
   - Performed Test Driven Development on all projects focused mainly on backend programming.
   - Converted from Windows to Linux (Ubuntu) for development stack and have been a full time user since then.
   - Currently, learning my way from Ubuntu to Arch.
   - Practiced a full agile development routine to roll out changes according to client requirements.
   - Worked on simple front-end interactive pages.
   - /Tech Knowledge/: Ruby on Rails, vanilla Javascript, SCSS, HTML5, and integration of other packages and Ubuntu.

   (/May - August 2014/) > *Web Developer Intern @ BetterWebPages*
   - Worked as a beginner full-stack developer and customized third-party packages to project requirements to deliver a fully operational website.
   - Handled client projects directly at a fresh startup.
   - /Tech Knowledge/: Python, Django, and vanilla Javascript.

** Projects

   (/September 2016 - Present/) > *Social Project for Children with Autism* \\
   With lack of materials to teach programming and simple robotics to specialized children, the projects goal was to design a curriculum for relatively higher functioning students.
   - We used multiple introductory test to analyze the intiial abilities of the students.
   - Designed a simple curriculum around their understanding ability which we hope will teach the students to program using a visual interface.
   - The bridge between robotics and programming was provided by Edison Robot. It can be programmed as well as controlled remotely in several ways.
   - For simple robotics, we used lego materials to create simple structures and place them with our robot.
   - Final assessment of the project was to combine the programming interface with the lego blocks to navigate around a simple maze.
   - Currently, we are ongoing the assesments of the final project.

   (/January - August 2016/) > *Interactive Animatronic Dragon @ SUTD Capstone* \\
   Established a simple DHCP network to allow two different sections of a mechanical dragon to communicate using Raspberry Pi. The different actions of the dragon were based on a simple statemachine which has fixed actions generated using a serial communication by Arduino through the Pi.

   (/March - May 2015/) > *A Simple Game for Android* \\
   Developed a fully operational game, in a team of 4, for a term project, which used LibGDX and Google Play Service.

   (/November - December 2014/) > *Android Travel App* \\
   Implented, in a team of 7, a travel application which maps out the shortest possible distance from a users current location to their destination based on the monetary input.

   (/November - December 2015/) > *Sequence Labelling System* \\
   Used Viterbi Algorithm to run Hidden Markov Model over a medium sized data sets of tweets to map tweets to user requirements. Our test algorithm managed an accuracy of 56% on experimental data.

** Skills

   Python, JavaScript, Express, Ruby, PHP, CSS, HTML, MySQL, PostgreSQL, Java, C, Django, Laravel, Ruby on Rails, Android, and LibGDX; Photoshop, Premier Pro, and After Effects.

** External Involvements

   (/June 2016/) - Participated in first NUS XCTF Competition. \\
   (/May 2016/)  - Finalists in APEX Business-IT Global Case Challenge 2016. \\
   (/July 2015/) - Attempted to develop a VR data visualization application in 1 day at Hackathon@SG50 Smart Nation.

** Interest

   Photography, Running, Non-Profit Social Events, Exploring Culture, Capture The Flag, Network Security, Physical Systems Security, and /Emacs/.

** Language

   English - Full Professional Proficiency | Bengali - Native Proficiency | Hindi and Urdu - Listening Proficiency.
