* Template Book Name
  :PROPERTIES:
  :GENRE:
  :PAGES:
  :YEAR:
  :AUTHOR:
  :START:
  :FINISH:
  :RATING: (out of 5)
  :END:

  (summary)

  (some quotes to remember)


* The Checklist Manifesto
  :PROPERTIES:
  :GENRE: SelfHelp
  :PAGES: 240
  :YEAR: 2011
  :AUTHOR: Atul Gawande
  :START: February 2018
  :FINISH: February 2018
  :RATING: 5
  :END:

  Checklist are a simple thing which saves a lot of suffereing: it saves lifes. Don't react to situations, use a checklist.

* Top Brain Bottom Brain
  :PROPERTIES:
  :GENRE: SelfHelp
  :PAGES: 208
  :YEAR: 2015
  :AUTHOR: Stephen Kosslyn, G. Wayne Miller
  :START: August 2017
  :FINISH: August 2017
  :RATING: 4
  :END:

  The book brings forth the idea of two different processes of perception, spatial and /surface recognition/. Instigating the observation further, they propose a different model of thought by which human being process their surroundings and make decisions based on what they observe. Backed by their scientific hypothesis, thought takes two different path through the top and bottom areas of brain which leads to different means of engaging an experience.

* David and Goliath
  :PROPERTIES:
  :GENRE: Nonfiction
  :PAGES: 352
  :YEAR: 2015
  :AUTHOR: Malcolm Gladwell
  :START: March 2017
  :FINISH: April 2017
  :RATING: 4.5
  :END:

  An advantage is not always an advantage; a disadvantage is not always a disadvantage. The book provides numerous insights into the lives of people, who has made best use of their disadvantages or could not reap their advantages. The idea is to look at the reality of the situation, process and understand the situation and then make a decision, just like David beat the Goliath my hurling a stone and winning.

* And the Mountains Echoed
  :PROPERTIES:
  :GENRE: fiction
  :PAGES: 448 pages
  :YEAR: 2014
  :AUTHOR: Khaled Husseini
  :START: <2018-06-19 Tue>
  :FINISH: <2018-06-30 Sat>
  :RATING: 4.5
  :END:

  A fictional but reality-grounded unfolding of lives of a family. Although, the book jumps from person to person without following the protagonists at every moment, it serves as a reminder on how unpredictible life is, how intertwined it is, and how people's behavior changes over time.

  I found a sad little fairy
  Beneath the shade of a paper tree
  I know a sad little fairy
  Who was blown away by the wind one night.

  Sur le pont d'Avignon
  L'on y danse, l'on y danse
  Sur le pont d'Avignon
  L'on y danse tous en rond.
