* =2017=
** Top Brain Bottom Brain
   :PROPERTIES:
   :GENRE:    SelfHelp
   :PAGES:    208
   :YEAR:     2015
   :AUTHOR:   Stephen Kosslyn, G. Wayne Miller
   :START:    August 2017
   :FINISH:   August 2017
   :RATING:   4
   :END:

   The book brings forth the idea of two different processes of
   perception, spatial and /surface recognition/. Instigating the
   observation further, they propose a different model of thought by
   which human being process their surroundings and make decisions
   based on what they observe. Backed by their scientific hypothesis,
   thought takes two different path through the top and bottom areas of
   brain which leads to different means of engaging an experience.

** David and Goliath
   :PROPERTIES:
   :GENRE:    Nonfiction
   :PAGES:    352
   :YEAR:     2015
   :AUTHOR:   Malcolm Gladwell
   :START:    March 2017
   :FINISH:   April 2017
   :RATING:   4.5
   :END:

   An advantage is not always an advantage; a disadvantage is not
   always a disadvantage. The book provides numerous insights into the
   lives of people, who has made best use of their disadvantages or
   could not reap their advantages. The idea is to look at the reality
   of the situation, process and understand the situation and then make
   a decision, just like David beat the Goliath my hurling a stone and
   winning.

* =2018=
** The Checklist Manifesto
   :PROPERTIES:
   :GENRE:    SelfHelp
   :PAGES:    240
   :YEAR:     2011
   :AUTHOR:   Atul Gawande
   :START:    February 2018
   :FINISH:   February 2018
   :RATING:   5
   :END:

   Checklist are a simple thing which saves a lot of suffereing: it
   saves lifes. Don't react to situations, use a checklist.

** And the Mountains Echoed
   :PROPERTIES:
   :GENRE:    fiction
   :PAGES:    448 pages
   :YEAR:     2014
   :AUTHOR:   Khaled Husseini
   :START:    July 2018
   :FINISH:   July 2018
   :RATING:   4.5
   :END:

   A fictional but reality-grounded unfolding of lives of a
   family. Although, the book jumps from person to person without
   following the protagonists at every moment, it serves as a reminder
   on how unpredictible life is, how intertwined it is, and how
   people's behavior changes over time.

   #+BEGIN_SRC 
   I found a sad little fairy
   Beneath the shade of a paper tree
   I know a sad little fairy
   Who was blown away by the wind one night.

   Sur le pont d'Avignon
   L'on y danse, l'on y danse
   Sur le pont d'Avignon
   L'on y danse tous en rond.
   #+END_SRC

* =2019=
** The Phoenix Project
  :PROPERTIES:
  :GENRE: Novel, Fiction
  :PAGES: 648
  :YEAR: 2013
  :AUTHOR: Gene Kim, George Spafford, and Kevin Behr
  :START:  January 2019
  :FINISH: February 2019
  :RATING: 4.5
  :END:

  It is very hard to adequately capture a teams performance for
  operations and delivery; it's especially harder to illustrate the
  mistakes as so many parameters are involved and so many decision
  that need to be made. But somehow, this book provide explains, from
  an operations perspective, how work should be tackled and managed to
  provide an optimum output for your company.

  There are 3 types of work: 

  - Planned
  - Request Change
  - Unplanned

** We Need To Talk
   :PROPERTIES:
   :GENRE:    SelfHelp
   :PAGES:    244
   :YEAR:     2017
   :AUTHOR:   Celeste Headlee
   :START:    March 2019
   :FINISH:   April 2019
   :RATING:   4
   :END:

   There is a lot of communication books in the market. Most of them
   provide common guidelines and/or "conversation starters". However,
   this book is the few ones which presents conversation as it should
   be - a method for understanding people - and provides the major
   points on how to be effective.

** The Idiot Brain
   :PROPERTIES:
   :GENRE:    Humor, SelfHelp
   :PAGES:    328
   :YEAR:     2016
   :AUTHOR:   Dean Burnett
   :START:    April 2019
   :FINISH:   June 2019
   :RATING:   3.5
   :END:

   This is a good book for information on the working of the brains in
   a scientific way in as much as the brain is known to act in
   /particular/ events or actions undertaken by people. For people who
   don't know or is interested to know why they suddenly forget things
   while walking to the kitchen or get an overview of how mental
   diseases occur, it is a good start. The writer does really well to
   go through dense information but in a humorus and fun way.

