#+TITLE: Resume
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/css/resume.css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
#+HTML_DOCTYPE: html5
#+OPTIONS: title:nil toc:nil num:nil html-postamble:nil html-preamble:nil html-style:nil html-scripts:nil
#+STARTUP: content
#+macro: span @@html:<span>@@$1@@html:</span>@@
#+macro: contact @@html:<span id="contact">@@@@html:<span>@@phone: $1@@html:</span>@@ @@html:<span>@@email: $2@@html:</span>@@@@html:</span>@@

* AHNAF SIDDIQI | {{{contact(+65 97342978, ahnafsidd[at]gmail.com)}}}
  :PROPERTIES:
  :CUSTOM_ID: resume-head
  :END:

   A learner, with 2 years of experience, carrying an interest in the
   field of network security, system architecture, database, and
   embedded systems.
   
** {{{span(EDUCATION)}}}
*** Singapore University of Technology and Design {{{span(Class of 2016)}}}

   Bachelor of Engineering with Honours majoring in Information Systems
   Technology and Design. \\
   Specialization: Security and Communications, Artificial Intelligence.

** {{{span(SKILLS)}}}

   *Core* - Python, C++, Docker, Docker Swarm, Docker-Compose, Git,
   Linux, GNU Make, Nginx.

   *Additional* - Javascript, Java, HTML, CSS, GDB, PostgreSQL,
   OpenCV, Ruby-on-Rails, SQLite, Laravel, Vue, Flutter.

** {{{span(WORK EXPERIENCE)}}}
*** Software Engineer in MicroSec Pte. Ltd. {{{span(Dec’17 - Now)}}}

    Lead engineer in the design, architecture, and development of a
    highly concurrent web service which is used in almost all customer
    projects. I have Sys. Admin and Intern management duties. I am
    also assisting in web development and customer support.

    - Architecting and developing a multithreaded concurrent network
      server which implements an end to end TLS 1.3 equivalent
      security stack for ultra-low powered embedded devices. It
      supports various protocols: LoRaWAN, Bluetooth, NBIoT, etc.
    - The web service implements Ellyptic Curve Crypto as the choice
      for Assymetric Key Exchange. AES CBC, AES GCM, and other crypto
      libraries are used for session keys.
    - Database schema design to ensure non-duplicate data accross
      multiple instances of the network server.
    - Development of continuous integration pipelines, managing cloud
      deployments of projects, ensuring high system availability and
      basic system administration.
    - Design and implementation of customer requested features and
      business logic in our Web Stack.
    - Supervision and management of interns to full time employees
      following companies operating procedure.
    - Use Case driven feature and sprint planning following Agile
      Principles.

    /Tech Stack/: C++, Python, Flask, SQLAlchemy, Hypothesis, Docker,
    Nginx, CI, Puppet, PostgreSQL, Vue, Angular, Valgrind, Wireshark,
    AWS EC2, Droplets.
    
*** Research Assistant in iTrust Research Center for CyberSecurity {{{span(Nov’16 - Oct’17)}}}

    Common Industrial Protocol (CIP) is a realtime network protocol
    being used in Secure Water Treatment (SWaT) testbed at SUTD. I
    followed specifications to implement a concurrent server to be
    used in simulation and various research purposes.

    - Analyzed and reconstructed high volume CIP packets of both TCP
      and UDP variants using wireshark.
    - Designed application using TDD and SOLID principles of OOP.
    - The library was used in a CaptureTheFlag event in an
      international inter-university competition for Secure
      Cyber-Physical (Scy-Phy) Systems Week.
    - Deployed and maintained the web challenge in Amazon EC2.
    - Analysed Networks for vulnerabilites in testbeds: SWat and EPIC.

    /Tech Stack/: Python, Flask, Wireshark, LxC, EtherNet/IP.

    /Publication/: A. Siddiqi, N. O. Tippenhauer, D. Mashima, and
    B. Chen, “On practical threat scenario testing in an electric
    power ics testbed,” in Proceedings of the cyber-physical system
    security workshop (cpss), co-located with asiaccs, 2018.

*** Web Developer in Souschef {{{span(Oct’16 - Jan’17)}}}

    Prototype, developed, and participated in the initial deployment
    of a configuration panel across mutliple remote machines.

    - Learnt and developed JS based web service following TDD
      principles.

    /Tech Stack/: Node, Python, Express.

*** Teaching Assistant in General Assembly {{{span(Aug - Sep’16)}}}

    Assisted instructors to teach students the basics of programming,
    web development, and CLI magic.

    - Taught Git, HTML, CSS, Javascript, and Express.
    - Managed multiple tasks including grading programming
      tests and evaluating student projects.

*** Web Developer Intern in Tinkerbox Studios {{{span(May - Aug’15)}}}

    Summer Internship where I developed business logic and implemented
    test cases of projects.

    - Practiced Test Driven Development using Ruby-on-Rails.
    - Worked on models, views, and controllers and wrote/refactored
      their new/old tests.
    - Implemented simple front-end interactive pages.

    /Tech Stack/: Rails, HTML, CSS, Heroku.

*** Web Developer Intern in BetterWebPages {{{span(May - Aug’14)}}}

    First work experience as a summer intern in a startup in infancy.

    - Worked as a beginner full-stack developer and customized
      third-party packages to project requirements to deliver a fully
      operational website.
    - Learned the major sections of the framework in two weeks and
      implemented started doing customer projects.
    - Rewrote django packages to suit the functionality requirements
      of projects.
    - Implemented some user interface elements which included bar
      chart, and pie charts.

    /Tech Stack/: Python, Django.

** {{{span(PROJECTS)}}}

*** Social Project for Children with Autism {{{span(Sep’16 - Nov’17)}}}

    Special needs children may be able to excel in programming. The
    project involved research, user data collection, designing, and
    testing a new curriculum to teach children basic coding concepts.

    - Analysing base performance by conducting several tests, surveys
      and measuring their memory and sequential task handling
      capability.
    - Data classification and curriculum design in a fun and analogous
      manner which teaches core concepts of programming.
    - Students who were able to partially communicate where able to
      perform all programming related tasks which involved recreating
      lego blocks from memory, reading and correctly recreating steps
      of visual code blocks, and finally solving difficult challenges
      with little to no assistance.

    /Stack/: Edison Robot, Research.

*** Capstone Project - Interactive Animatronic Dragon {{{span(Jan - Aug’16)}}}

    An animatronic dragon which scans its vicinity using OpenCV
    toolkit triggering movement to its multiple sections in the
    body. I setup the network for the communication between different
    paths and helped programmed some motors. 

    - Worked in a student team of 6 people from different technical
      tracks.
    - Implemented an ad-hoc network with static IP for P2P connections
      between two RaspberryPi.
    - Developed a state machine to map and categorize different
      outputs to user inputs.
    - Assisted in programming the movement of mechanical sections by
      interfacing physical mechanical relays.

    /Tech Stack/: Python, OpenCV.

# Deprecated: This is kept just for collection purposes. This project
# was never completed or even crossed the halfway point.
# *** Web Development - Non-academic University Project {{{span(Dec’15 - July’16)}}}

#     Create an in-house seat reservation platform for students to use
#     several office spaces.

#     - Developed the platform using Laravel and hosted in university server.

#     /Tech Stack/: Laravel, Artisan, PHP.

** {{{span(ACTIVITIES)}}}

   *External Involvements* - NUS XCTF 2016, Finalists for APEX
   Business-IT Global Case Challenge 2016, SG50 Hackathon 2015 Smart
   Nation, Secretary for University Photography Club.

   *Interests* - Photography, Running, Non-Profit Social Events,
   Exploring Culture, CaptureTheFlag, Network Security, Physical
   Systems Security, Linux, Arch and Emacs.

   *Languages* - English (Full Professional Proficiency), Bengali
   (Native).

