#+TITLE: Resume
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../static/css/resume.css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
#+HTML_DOCTYPE: html5
#+OPTIONS: title:nil toc:nil num:nil html-postamble:nil html-preamble:nil html-style:nil html-scripts:nil
#+STARTUP: content
#+macro: span @@html:<span>@@$1@@html:</span>@@
#+macro: contact @@html:<span id="contact">@@@@html:<span>@@phone: $1@@html:</span>@@ @@html:<span>@@email: $2@@html:</span>@@@@html:</span>@@

* AHNAF SIDDIQI | {{{contact(+65 97342978, ahnafsidd[at]gmail.com)}}}
  :PROPERTIES:
  :CUSTOM_ID: resume-head
  :END:

   I am a curious individual holding a keen interest in the field of
   network system architecture, embedded systems, and security. I
   strive for learning and continous improvement and bring my
   experience in design thinking to provide quick feedback cycle.
   
** {{{span(EDUCATION)}}}
*** Singapore University of Technology and Design {{{span(Class of 2016)}}}

   Bachelor of Engineering with Honours majoring in Information Systems
   Technology and Design. \\
   Specialization: Security and Communications, Artificial Intelligence.

** {{{span(SKILLS)}}}

   *Core* - Python, C++, Docker, Git, Linux, GNU Make.

   *Additional* - Javascript, Java, HTML, CSS, GDB, PostgreSQL,
   OpenCV, Ruby-on-Rails, SQLite, Laravel, Vue, Flutter.

** {{{span(WORK EXPERIENCE)}}}
*** Software Engineer in MicroSec Pte. Ltd. {{{span(Dec’17 - Present)}}}

    A Deep Tech IoT company where I am leading the technical design,
    development, and maintenance of a web server, System
    Administration, and Intern management and
    supervision. Additionally, I am assisting in Backend Web
    Development, and Customer Support.

    - Engineering a multithreaded concurrent network server which
      provides an end to end TLS 1.3 equivalent security for ultra-low
      powered embedded devices which supports various protocols: LoRaWAN,
      Bluetooth, NBIoT, etc.
    - Database schema design to ensure non-duplicate data accross
      multiple instances of the network server.
    - Supervision and training to develop interns to full time
      employees following companies work culture.
    - Intern Management on an average of 5 candidates per batch.
    - Development of continuous integration pipelines, managing cloud
      deployments for pilot projects, ensuring high system
      availability and basic system administration.
    - Development of new features and business logic in our Web Stack.
    - Use Case driven feature planning and sprint planning
      following Agile Principles.
    - Multiple customer support duties on-site and off-site to
      install, update, and maintain our products.

    /Tech Stack/: C++, Python, Flask, SQLAlchemy, Hypothesis, Docker,
    Nginx, Gitlab CI, Puppet, PostgreSQL, Vue, Angular, Valgrind,
    Wireshark, AWS EC2, Droplets.
    
*** Research Assistant in iTrust Research Center for CyberSecurity {{{span(Nov’16 - Oct’17)}}}

    Developed and implemented a network protocol library to reproduce
    packets of Common Industrial Protocol (CIP) for Secure Water
    Treatment (SWaT) testbed.

    - Analyzed and reconstructed high volume CIP packets for both TCP
      and UDP section using wireshark.
    - Designed and implemented an API for the package using TDD and
      SOLID principles of OOP.
    - The library was used in a CaptureTheFlag competion in
      an international inter-university competition for Secure
      Cyber-Physical (Scy-Phy) Systems Week.
    - Deployed and maintained a web challenge in Amazon EC2 for the
      competition.
    - Research and Network Analysis for vulnerabilites in testbeds:
      SWat and EPIC.

    /Tech Stack/: Python, Flask, Wireshark, LxC, EtherNet/IP.

    /Publication/: A. Siddiqi, N. O. Tippenhauer, D. Mashima, and
    B. Chen, “On practical threat scenario testing in an electric
    power ics testbed,” in Proceedings of the cyber-physical system
    security workshop (cpss), co-located with asiaccs, 2018.

*** Web Developer in Souschef {{{span(Oct’16 - Jan’17)}}}

    Prototyping and development of a configuration panel which takes
    user input, stores in a DB, and uploads them across multiple remote
    machines

    - Improve my knowledge in the fundamentals of JS, Express, and
      TDD. A part-time adventure.

    /Tech Stack/: Node, Python, Express.

*** Teaching Assistant in General Assembly {{{span(Aug - Sep’16)}}}

    Assisted instructor to help teach students the basics of web
    development.

    - Taught CLI, git, HTML, CSS, Javascript, and Express.
    - Managed multiple tasks which included analyzing project codes
      and programming tests.

*** Web Developer Intern in Tinkerbox Studios {{{span(May - Aug’15)}}}

    Programmed backend functionality and wrote test cases for projects
    following agile methodology.

    - Practiced Test Driven Development using Ruby-on-Rails.
    - Worked on models, views, and controllers and wrote/refactored
      their new/old tests.
    - Implemented simple front-end interactive pages.

   /Tech Stack/: Rails, HTML, CSS, Heroku.

** {{{span(PROJECTS)}}}

*** Social Project for Children with Autism {{{span(Sep’16 - Nov’17)}}}

    Researched and designed a new curriculum to teach programming
    concepts and simple robotics to special needs children.

    - Analyzed the students initial performance by taking several
      tests which measured their memory and sequential task handling
      abilities.

    - The curriculum used Edison robot to provide the visual interface
      for programming and Lego bricks as a simple building block for
      robotics and integrates them.

    /Stack/: Edison Robot, Academic Research.

*** Capstone Project - Interactive Animatronic Dragon {{{span(Jan - Aug’16)}}}

    Established a network to transfer data between multiple sections
    of a prototype of an animatronic dragon which detects user
    movements in its peripherals to provide interactive feedback. The
    full project includes design and construction of mechanical,
    aesthetic, and user experience.

    - Implemented an ad-hoc network with static IP for P2P connections
      between two RaspberryPi.
    - Developed a state machine to categorize different out puts
      according to user inputs.
    - Used Open CV to detect user movement to be used as inputs for
      the statemachine.
    - Worked in a student team of 6 people from different technical
      tracks.

    /Tech Stack/: Python, OpenCV.

*** Web Development - Non-academic University Project {{{span(Dec’15 - July’16)}}}

    Create a platform for a booking system of graduate students seating.

    - Developed the platform using Laravel and hosted in university server.

    /Tech Stack/: Laravel, Artisan, Php.

** {{{span(ACTIVITIES)}}}

   *External Involvements* - NUS XCTF 2016, Finalists for APEX
   Business-IT Global Case Challenge 2016, SG50 Hackathon 2015 Smart
   Nation, Secretary for University Photography Club.

   *Interests* - Photography, Running, Non-Profit Social Events,
   Exploring Culture, CaptureTheFlag, Network Security, Physical
   Systems Security, Linux, Arch and Emacs.

   *Languages* - English (Full Professional Proficiency), Bengali
   (Native).

