#+TITLE: Resume
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/resume.css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
#+HTML_DOCTYPE: html5
#+OPTIONS: title:nil toc:nil num:nil html-postamble:nil html-preamble:nil html-style:nil html-scripts:nil
#+STARTUP: content
#+macro: span @@html:<span>@@$1@@html:</span>@@
#+macro: contact @@html:<span id="contact">@@@@html:<span>@@phone: $1@@html:</span>@@ @@html:<span>@@email: $2@@html:</span>@@@@html:</span>@@

* AHNAF SIDDIQI | {{{contact(+65 97342978, ahnafsidd@gmail.com)}}}
  :PROPERTIES:
  :CUSTOM_ID: resume-head
  :END:

** {{{span(EDUCATION)}}}
*** Singapore University of Technology and Design {{{span(Class of 2016)}}}

   Bachelor of Engineering with Honours majoring in Information Systems
   Technology and Design. \\
   Specialization: Security and Communications, Artificial Intelligence.

** {{{span(SKILLS)}}}

   *Core Competency* - Python, C++, Linux, Docker, Bash, HTML,
   PostgreSQL, Git, SQLite, Makefile.
   
   *Familiar with* - Javascript, Java, AWS, CSS, MySQL, OpenCV
   Ruby-on-Rails, Laravel, Vue, Flutter.

** {{{span(WORK EXPERIENCE)}}}
*** Backend Developer in MicroSec Pte. Ltd. {{{span(Dec’17 - Present)}}}

    Developed and implemented a network protocol library to reproduce
    packets of Common Industrial Protocol for Secure Water Treatment
    (SWaT) testbed to be utilized for various simulations in research.

*** Research Assistant in iTrust Research Center for CyberSecurity {{{span(Nov’16 - Oct’17)}}}

    Developed and implemented a network protocol library to reproduce
    packets of Common Industrial Protocol for Secure Water Treatment
    (SWaT) testbed to be utilized for various simulations in research.

    - Analyzed and reconstructed CIP packets for both TCP and UDP
      section using wireshark.
    - Designed and implemented an API for the package using TDD and
      SOLID principles of OOP.
    - The library was used in a CaptureTheFlag competion in
      aninternational inter-university competition for
      SecureCyber-Physical(Scy-Phy) Systems Week.
    - Developed, deployed, and maintained a webchallenge in AmazonEC2
      for the competition.
    - Used linux containers,uniquely mapped to each team,to run
      privileged code in a secure way.

*** Web Developer in Souschef {{{span(Oct’16 - Jan’17)}}}

    Developed a configuration panel which takes user input,stores in a
    DB, and uploads them across multiple remote machines(prototypes).

    - Improve my knowledge in the fundamentals of JS, Express, and
      TDD. A part-time adventure.

*** Teaching Assistant in General Assembly {{{span(Aug - Sep’16)}}}

    Assisted instructor to help teach the basics of web development
    from scratch.

    - Taught CLI, git, HTML, CSS, Javascript, and Express to students.
    - Managed multiple tasks which included analyzing project codes
      and programming tests.

*** Web Developer Intern in Tinkerbox Studios {{{span(May - Aug’15)}}}

    Programmed backend functionality and wrote test cases for projects
    following agile methodology.

    - Practiced TestDrivenDevelopment using Ruby-on-Rails.
    - Worked on models, views, and controllers and wrote/refactored
      their new/old tests.
    - Implemented simple front-end interactive pages.

** {{{span(PROJECTS)}}}

*** Social Project for Children with Autism {{{span(Sep’16 - Nov’17)}}}

    Designed a new curriculum to teach programming and simple robotics
    to special needs children.

    - Analyzed the students initial performance by taking several
      tests which measured their memory and sequential task handling
      abilities.
    - The curriculum used Edison robot to provide the visual interface
      for programming and Lego bricks as a simple building block for
      robotics and integrates them.

*** Capstone Project - Interactive Animatronic Dragon {{{span(Jan - Aug’16)}}}

    Established a network to transfer data between multiple sections
    of a prototype of an animatronic dragon which detects users in its
    peripherals and performs action

    - Implemented an ad-hoc network with static IP for P2P connections
      between two RaspberryPi.
    - Developed a state machine to categorize different out puts
      according to user inputs.
    - Used Open CV to detect user movement to be used as inputs for
      the statemachine.

*** Web Development - Non-academic University Project {{{span(Dec’15 - July’16)}}}

    Create a platform for a booking system of graduate students seating.

    - Developed the platform using Laravel and hosted in university server.

** {{{span(ACTIVITIES)}}}

   *External Involvements* - NUS XCTF 2016, Finalists for APEX
   Business-IT Global Case Challenge 2016, SG50 Hackathon 2015 Smart
   Nation, Secretary for University Photography Club.

   *Interests* - Photography, Running, Non-Profit Social Events,
   Exploring Culture, CaptureTheFlag, Network Security, Physical
   Systems Security, Linux, Arch and Emacs.

