#+TITLE: Resume
#+LATEX_HEADER: \usepackage{parskip}
#+LATEX_HEADER: \usepackage[margin=0.9in]{geometry}
#+LATEX_HEADER: \usepackage{titling} \setlength{\droptitle}{-2.5cm}
#+OPTIONS: author:nil num:1 toc:nil date:nil

  #+BEGIN_CENTER
  Ahnaf Siddiqi | http://remmihsorp.github.io | ahnafsidd@gmail.com
  #+END_CENTER

  #+BEGIN_EXAMPLE
  This is an abridged resume which I use publicly.
  #+END_EXAMPLE

** Education

   (/Class of 2016/) > *Singapore University of Technology and Design*

   Bachelor of Engineering with major in Information Systems Technology and Design. \\
   Focus Tracks: Security and Communications, Artificial Intelligence.

** Experience

   (/November 2016 - Present/) > *Research Assistant @ Singapore University of Technology and Design*
   Developed and implemented a network protocol library to reproduce packets of Common Industrial Protocol for Secure Water Treatment (SWaT) testbed to be utilized for various simulations in research.

   • Analyzed and reconstructed CIP packets for both TCP and UDP sections using wireshark.
   • Designed and implemented an API for the package using TDD and SOLID principles of OOP.
   • The library was used in a Capture The Flag in an international inter-university competition for Secure Cyber-Physical (Scy-Phy) Systems Week at SUTD.
   • Developed, deployed and maintained a web challenge in Amazon EC2 for the competition.
   • Used linux containers, uniquely mapped to each team, to run privileged code in a secure way.

   (/October 2016 - January 2017/) > *Web Developer @ Souschef*
   Developed a configuration panel which takes user input, stores in a DB, and uploads them across multiple remote machines(prototypes).
   • Worked in a small team of 3 to develop a web application in nodejs.
   • Improve my knowledge in the fundamentals of JS, Express, and TDD. A part-time adventure.

   (/August - September 2016/) > *Teaching Assistant @ General Assembly*
   Assisted instructor to help teach the basics of web development from scratch.
   • Taught CLI, git, HTML, CSS, Javascript, and Express to students.
   • Managed multiple tasks which included analyzing project codes and programming tests.

   (/May - August 2015/) > *Web Developer Intern @ Tinkerbox Studios*
   • Performed Test Driven Development on all projects focused mainly on backend programming.
   • Converted from Windows to Linux (Ubuntu) for development stack and have been a full time user since then.
   • Practiced a full agile development routine to roll out changes according to client requirements.
   • Worked on simple front-end interactive pages.
   • Learned Rails and RSpec test suite in two weeks before being assigned to a live project.

   (/May - August 2014/) > *Web Developer Intern @ BetterWebPages*
   • Worked as a beginner full-stack developer and customized third-party packages to project requirements to deliver a fully operational website.
   • First experience with web development and Django.
   • Learned the entire framework in two weeks and implemented the feature functionalities.
   • Rewrote django packages to suit the functionality requirements of projects.
   • Implemented some user interface elements which included bar chart, and pie charts.

** Projects

   (/September 2016 - Present/) > *Social Project for Children with Autism* \\
   With lack of materials to teach programming and simple robotics to specialized children, the projects is about designing and developing a simple but comprehensive curriculum which introduces basics of programming and simple robotics for relatively higher functioning students.

   • We used multiple introductory test to analyze the intiial abilities of the students.
   • Designed a simple curriculum around their understanding ability which we hope will teach the students to program using a visual interface.
   • The bridge between robotics and programming was provided by Edison Robot. It can be programmed as well as controlled remotely in several ways.
   • For simple robotics, we used lego materials to create simple structures and place them with our robot.
   • Final assessment of the project was to combine the programming interface with the lego blocks to navigate around a simple maze.

   (/January - August 2016/) > *Interactive Animatronic Dragon @ SUTD Capstone* \\
   Established a simple DHCP network to allow two different sections of a mechanical dragon to communicate using Raspberry Pi. The different actions of the dragon were based on a simple statemachine which has fixed actions generated using a serial communication by Arduino through the Pi.

   (/March - May 2015/) > *A Simple Game for Android* \\
   Developed a fully operational game, in a team of 4, for a term project, which used LibGDX and Google Play Service.

   (/November - December 2014/) > *Android Travel App* \\
   Implented, in a team of 7, a travel application which maps out the shortest possible distance from a users current location to their destination based on the monetary input.

   (/November - December 2015/) > *Sequence Labelling System* \\
   Used Viterbi Algorithm to run Hidden Markov Model over a medium sized data sets of tweets to map tweets to user requirements. Our test algorithm managed an accuracy of 56% on experimental data.

** Skills

   Python, JavaScript, Express, Ruby, PHP, CSS, HTML, MySQL, PostgreSQL, Java, C, Django, Laravel, Ruby on Rails, Android, and LibGDX; Photoshop, Premier Pro, and After Effects.

** External Involvements

   (/June 2016/) - Participated in first NUS XCTF Competition. \\
   (/May 2016/)  - Finalists in APEX Business-IT Global Case Challenge 2016. \\
   (/July 2015/) - Attempted to develop a VR data visualization application in 1 day at Hackathon@SG50 Smart Nation.

** Interest

   Photography, Running, Non-Profit Social Events, Exploring Culture, Capture The Flag, Network Security, Physical Systems Security, and /Emacs/.

** Language

   English - Full Professional Proficiency | Bengali - Native Proficiency | Hindi and Urdu - Listening Proficiency.
