#+TITLE: Grammar
#+DATE: <2020-02-13 Thu>
#+GENRE: Grammar
#+ESSENCE: What is Grammar?
#+TAG: Sentence
#+MODIFIED: 
#+STARTUP: showall

Let's think of sports. And let's pick ... a team game - floorball. In this
game as long as you place the ball successfully into your opponents net, you
score. It really does not matter how you do it, just that you are able to.

However, strategies come into play. If you form a plan to engage a certain
pattern against your opponent, chances are you are going to increase your
probablity of scoring. When you think of different styles, chances are you are
thinking of several possibilites of attacking or defending in the game. 

Grammar is just that: a way to form patterns in writing to communicate ideas
comprehensively. Instead of joining words randomly, the idea is to use
coherent sentences to clearly express your thoughts. There are some basic
methods (building blocks) analogous to the rules of passing a ball, and there
are advance methods.

There are different styles of grammar too. Just like how you would formulate
your patterns differently against various teams: attacking, defensive,
amateurs and advanced, there are different ways of expressing grammar: formal
and informal. It depends on where you are residing in the world. 

However, generally speaking, formal written sentences have standard rules with
minimal variations and its generally accepted by the world.

So, let's dive in to learn the structures and patterns of grammar. 
