GROUPS = climbing ctfs devops emacs frontend graphs

index: code algo code/index algo/index
	echo "code index place" > index
	echo "algo index place" >> index
	echo ".. index generated" > /dev/null

code/index: code
	echo "code inner index place" > code/index
	echo "... code/index generated" > /dev/null

algo/index: algo
	echo "algo inner index place" > algo/index
	echo "... code/index generated" > /dev/null
